### ISSUE TITLE
Error When Trying to View the Project In the Browser

### ISSUE THREAD

**Issue by eparker28** [jonhilt/a-simple-blog-blazor-wasm#1]
When trying to launch the project in the browser, even when no changes are made to the latest github source version, I receive the standard "Unhandled error has occurred" with the default prompt to "Reload".

I am attaching the error as shown in the browser console.
[ConsoleMesaage.log](https://github.com/jonhilt/a-simple-blog-blazor-wasm/files/5900631/ConsoleMesaage.log)

**Comment by jonhilt** [comment]
Hey,

Are you launching the .Client or .Server project?

For everything to work properly you'll need to make sure you're launching the .Server project as it hosts the WASM application (as well as the backend API with which the WASM application interacts).

If you are launching the .Server project but still getting an issue, let me know and I'll take another look 👍

**Comment by eparker28** [comment]
Jon,

I am so embarrassed that the solution was simply to set the Server project as the startup project. I thought I had double checked that multiple times. Well, thanks for the fast response. I do enjoy working through your course.

Erik Parker
214-995-1011
Eparker28@hotmail.com

**Comment by jonhilt** [comment]
Absolutely no need to be embarrassed, it's easily done!

Glad you're back up and running now.
